
USE TEST_DATABASE
GO
ALTER AUTHORIZATION ON SCHEMA::[db_owner] TO [DOMAIN\serviceaccount]
GO

-- Disable users
update USERINFO
   set [ENABLE]=0
 where USERINFO.id NOT IN ('aos','batch','axcon','Admin','ifc','usr01','usr02');

--Space saving measures
TRUNCATE TABLE DATABASELOG
TRUNCATE TABLE SYSDATABASELOG
TRUNCATE TABLE EVENTCOMPANYRULE
TRUNCATE TABLE EVENTCUD
TRUNCATE TABLE EVENTINBOX
TRUNCATE TABLE EVENTINBOXDATA
TRUNCATE TABLE EVENTPARAMETERS
TRUNCATE TABLE EVENTRULE
TRUNCATE TABLE EVENTRULEDATA
TRUNCATE TABLE EVENTRULEFIELD
TRUNCATE TABLE EVENTRULEIGNORE
TRUNCATE TABLE EVENTRULEIGNOREAGGREGATION
TRUNCATE TABLE EVENTRULEREL
TRUNCATE TABLE EVENTRULERELDATA
TRUNCATE TABLE EVENTSYSTEMPARAMETERS
TRUNCATE TABLE SYSOUTGOINGEMAILTABLE
TRUNCATE TABLE SYSOUTGOINGEMAILDATA
TRUNCATE TABLE PRINTJOBPAGES
TRUNCATE TABLE PRINTJOBHEADER
TRUNCATE TABLE BATCHHISTORY
TRUNCATE TABLE BATCHJOBHISTORY
TRUNCATE TABLE BATCHCONSTRAINTSHISTORY
--Avoid sending an email to real customers by accident + save space
TRUNCATE TABLE SYSEMAILTABLE
TRUNCATE TABLE SYSOUTGOINGEMAILTABLE  
--Remove SysSQMSettings gymnastics to avoid problems with having the same guid for test and live in cache file names
TRUNCATE TABLE SYSSQMSETTINGS;
-- avoid sessions related SSRS problems
TRUNCATE TABLE SYSSERVERSESSIONS;
TRUNCATE TABLE SYSCLIENTSESSIONS;
--Remove Enterprise portal link
TRUNCATE TABLE EPGLOBALPARAMETERS;
--remove SSRS Servers configs
TRUNCATE TABLE SRSSERVERS;

--Outgoing messages - for electronic comms exports/imports - avoid picking live things in TEST
UPDATE AIFCHANNEL 
   SET TRANSPORTADDRESS = REPLACE(TRANSPORTADDRESS,'\Live\','\Test\')
 WHERE TRANSPORTADDRESS  like '\\%'
   AND NOT TRANSPORTADDRESS LIKE '%\Test\%'

UPDATE AIFCHANNEL 
   SET TRANSPORTADDRESS = REPLACE(TRANSPORTADDRESS,'Live','Test')
 WHERE TRANSPORTADDRESS  like '\\%'

--Change the Organization name to TEST + OrigName while observing the max 100 chars limit
UPDATE A
   SET A.NAME = SUBSTRING('TEST ' + A.NAME,1,100),
       A.NAMEALIAS = SUBSTRING('TEST ' + A.NAMEALIAS,1,20)
  FROM DIRPARTYTABLE A
 WHERE A.INSTANCERELATIONTYPE=41
   AND NOT A.NAME like 'TEST%';

--Change the Organization street to Test street 7
UPDATE A
   SET A.[ADDRESS] = 'Test street 7' + CHAR(10) + A.ZIPCODE + ' ' + A.CITY,
       A.STREET = 'Test street 7'
  FROM LOGISTICSPOSTALADDRESS A
  JOIN DIRPARTYLOCATION B ON (A.LOCATION = B.RECID)
  JOIN DIRPARTYTABLE C ON (C.RECID = B.PARTY)
 WHERE C.INSTANCERELATIONTYPE=41
   AND A.[ADDRESS] NOT LIKE 'Test street 7%'; --OM Organization

UPDATE A
   SET A.[DESCRIPTION] = SUBSTRING('Test ' + A.[DESCRIPTION],1,60)
  FROM LOGISTICSLOCATION A
  JOIN DIRPARTYLOCATION B ON (A.RECID = B.RECID)
  JOIN DIRPARTYTABLE C ON (C.RECID = B.PARTY)
 WHERE C.INSTANCERELATIONTYPE=41
  AND A.[DESCRIPTION] NOT LIKE 'Test %'; --OM Organization

TRUNCATE TABLE SYSSERVERCONFIG;
DBCC SHRINKFILE (N'FILENAME' , 168000)
GO

GO
DBCC SHRINKFILE (N'FILENAME_log')
GO

